# Files in the project (Relative to this CMAKE file)
FILE(GLOB BIOGEARS_TEST_FILES
	"test/cpp/*.h"
	"test/cpp/*.cpp"
)
SET(SOURCE ${BIOGEARS_TEST_FILES})
FILE(GLOB BIOGEARS_CIRCUITS_TEST_FILES
	"test/cpp/Circuits/*.h"
	"test/cpp/Circuits/*.cpp"
)
LIST(APPEND SOURCE ${BIOGEARS_CIRCUITS_TEST_FILES})
FILE(GLOB BIOGEARS_ENGINE_TEST_FILES
	"test/cpp/Engine/*.h"
	"test/cpp/Engine/*.cpp"
)
LIST(APPEND SOURCE ${BIOGEARS_ENGINE_TEST_FILES}) 
FILE(GLOB BIOGEARS_SYSTEMS_TEST_FILES
	"test/cpp/Systems/*.h"
	"test/cpp/Systems/*.cpp"
)
LIST(APPEND SOURCE ${BIOGEARS_SYSTEMS_TEST_FILES}) 
# Create Filters
SOURCE_GROUP("" FILES ${BIOGEARS_TEST_FILES})
SOURCE_GROUP("Circuits" FILES ${BIOGEARS_CIRCUITS_TEST_FILES})
SOURCE_GROUP("Engine" FILES ${BIOGEARS_ENGINE_TEST_FILES})
SOURCE_GROUP("Systems" FILES ${BIOGEARS_SYSTEMS_TEST_FILES})
# The DLL we are building
ADD_LIBRARY(BioGearsEngineTest SHARED ${SOURCE})
# Preprocessor Definitions and Include Paths
SET(ENGINE_TEST_FLAGS)
SET(ENGINE_TEST_FLAGS "${ENGINE_TEST_FLAGS} -D TEST_EXPORTS")
SET(ENGINE_TEST_FLAGS "${ENGINE_TEST_FLAGS} -D UNICODE")
SET(ENGINE_TEST_FLAGS "${ENGINE_TEST_FLAGS} -D _UNICODE")
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/cpp)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/test/cpp)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../cdm/cpp)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../schema/cpp)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/log4cpp/include)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/Eigen-3.3.1)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/${XERCES_VER}/src)
TARGET_INCLUDE_DIRECTORIES(BioGearsEngineTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/${XSD_VER}/libxsd)

SET_TARGET_PROPERTIES(BioGearsEngineTest PROPERTIES COMPILE_FLAGS "${ENGINE_TEST_FLAGS}" PREFIX "")

IF(APPLE)
    SET_TARGET_PROPERTIES(BioGearsEngineTest PROPERTIES MACOSX_RPATH ON)
ENDIF()

# Dependent Libraries
TARGET_LINK_LIBRARIES(BioGearsEngineTest BioGearsEngine)
# Generate cxx/hxx files from xsd
# Copy to the bin
SET(CONFIG_STRING)
IF(WIN32)
  SET(CONFIG_STRING ${CMAKE_CFG_INTDIR})
ELSE()
  STRING(TOLOWER ${CMAKE_BUILD_TYPE} CONFIG_STRING)
ENDIF()

ADD_CUSTOM_COMMAND(TARGET BioGearsEngineTest POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:BioGearsEngineTest> ${CMAKE_CURRENT_SOURCE_DIR}/../../bin/${CONFIG_STRING}${EX_CONFIG}
)			   
