# Files in the project (Relative to this CMAKE file)
FILE(GLOB CDM_TEST_FILES
	"test/cpp/*.h"
	"test/cpp/*.cpp"
)
SET(SOURCE ${CDM_TEST_FILES})

FILE(GLOB CDM_CIRCUITS_TEST_FILES
	"test/cpp/Circuits/*.h"
	"test/cpp/Circuits/*.cpp"
)
LIST(APPEND SOURCE ${CDM_CIRCUITS_TEST_FILES}) 

FILE(GLOB CDM_PATIENT_TEST_FILES
	"test/cpp/Patients/*.h"
	"test/cpp/Patients/*.cpp"
)
LIST(APPEND SOURCE ${CDM_PATIENT_TEST_FILES}) 

FILE(GLOB CDM_COMPARTMENT_TEST_FILES
	"test/cpp/Compartments/*.h"
	"test/cpp/Compartments/*.cpp"
)
LIST(APPEND SOURCE ${CDM_COMPARTMENT_TEST_FILES}) 

FILE(GLOB CDM_PROPERTIES_TEST_FILES
	"test/cpp/Properties/*.h"
	"test/cpp/Properties/*.cpp"
)
LIST(APPEND SOURCE ${CDM_PROPERTIES_TEST_FILES}) 

FILE(GLOB CDM_SCENARIO_TEST_FILES
	"test/cpp/Scenario/*.h"
	"test/cpp/Scenario/*.cpp"
)
LIST(APPEND SOURCE ${CDM_SCENARIO_TEST_FILES}) 

FILE(GLOB CDM_SUBSTANCES_TEST_FILES
	"test/cpp/Substances/*.h"
	"test/cpp/Substances/*.cpp"
)
LIST(APPEND SOURCE ${CDM_SUBSTANCES_TEST_FILES}) 

# Create Filters
SOURCE_GROUP("" FILES ${CDM_TEST_FILES})
SOURCE_GROUP("Circuits" FILES ${CDM_CIRCUITS_TEST_FILES})
SOURCE_GROUP("Compartments" FILES ${CDM_COMPARTMENT_TEST_FILES})
SOURCE_GROUP("Patients" FILES ${CDM_PATIENT_TEST_FILES})
SOURCE_GROUP("Properties" FILES ${CDM_PROPERTIES_TEST_FILES})
SOURCE_GROUP("Scenario" FILES ${CDM_SCENARIO_TEST_FILES})
SOURCE_GROUP("Substances" FILES ${CDM_SUBSTANCES_TEST_FILES})
# The DLL we are building
ADD_LIBRARY(CommonDataModelTest SHARED ${SOURCE})
# Preprocessor Definitions and Include Paths
SET(CDM_TEST_FLAGS)
SET(CDM_TEST_FLAGS "${CDM_TEST_FLAGS} -D TEST_EXPORTS")
SET(CDM_TEST_FLAGS "${CDM_TEST_FLAGS} -D UNICODE")
SET(CDM_TEST_FLAGS "${CDM_TEST_FLAGS} -D _UNICODE")
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../schema/cpp)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/cpp)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/test/cpp)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/Eigen-3.3.1)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/log4cpp/include)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/${XERCES_VER}/src)
TARGET_INCLUDE_DIRECTORIES(CommonDataModelTest PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../lib/${XSD_VER}/libxsd)
SET_TARGET_PROPERTIES(CommonDataModelTest PROPERTIES COMPILE_FLAGS "${CDM_TEST_FLAGS}" PREFIX "")

IF(APPLE)
    SET_TARGET_PROPERTIES(CommonDataModelTest PROPERTIES MACOSX_RPATH ON)
ENDIF()

# Dependent Libraries
TARGET_LINK_LIBRARIES(CommonDataModelTest CommonDataModel)
# Generate cxx/hxx files from xsd
# Copy to the bin
SET(CONFIG_STRING)
IF(WIN32)
  SET(CONFIG_STRING ${CMAKE_CFG_INTDIR})
ELSE()
  STRING(TOLOWER ${CMAKE_BUILD_TYPE} CONFIG_STRING)
ENDIF()

ADD_CUSTOM_COMMAND(TARGET CommonDataModelTest POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:CommonDataModelTest> ${CMAKE_CURRENT_SOURCE_DIR}/../../bin/${CONFIG_STRING}${EX_CONFIG}
)			   
